import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://v2.dev.lilyogis.in/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('rishav.r@rocketlearning.org');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Rishabh123!@#');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Rishabh1309!@');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('summary').filter({ hasText: 'Demographics' }).click();
  await page.getByText('Schools', { exact: true }).click();
  await page.getByRole('link', { name: 'Browse Schools' }).click();
  await page.getByRole('textbox', { name: 'Search by UDISE code' }).click();
  await page.getByRole('textbox', { name: 'Search by UDISE code' }).fill('9999999999');
  await page.locator('.rounded-e-lg > .btn').click();
  await page.getByRole('cell', { name: 'test' }).click();
  await page.getByRole('cell', { name: '9999999999' }).click();
  await page.locator('#schools').getByRole('link').click();
  await page.locator('#create-school').getByText('Create School').click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('textbox', { name: 'UDISE Code *' }).click();
  await page.locator('div:nth-child(4) > div > .select').click();
  await page.getByRole('textbox', { name: 'Select District *' }).press('Escape');
  await page.locator('div:nth-child(5) > div > .select').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.locator('#schools').getByRole('button').click(); 
  await page.getByRole('main').locator('form div').filter({ hasText: 'Search by state name' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Select State' }).press('Escape');
  await page.locator('#schools').getByRole('button').click();
  await page.getByRole('main').locator('form div').filter({ hasText: 'Search by district name' }).nth(2).click();
  await page.locator('div:nth-child(4) > div > .select').click();
  await page.getByRole('textbox', { name: 'School Type' }).press('Escape');
  await page.locator('#schools').getByRole('button').click();
  await page.locator('div:nth-child(5) > div > .select').click();
  await page.getByRole('main').locator('form div').filter({ hasText: 'Search by project name' }).nth(2).click();
  await page.locator('.pb-5 > div > .flex > .btn').click();
  await page.getByRole('textbox', { name: 'Search by UDISE code' }).click();
  await page.getByRole('textbox', { name: 'Search by UDISE code' }).fill('9999999999');
  await page.locator('.rounded-e-lg > .btn').click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.goto('https://v2.dev.lilyogis.in/schools/view/253182');
  await page.getByRole('main').locator('form div').filter({ hasText: 'Choose type * UPS Select from' }).nth(1).click();
  await page.getByRole('main').locator('form div').filter({ hasText: 'Select District Adilabad' }).nth(1).click();
  await page.getByRole('main').locator('form div').filter({ hasText: 'Select Beat/sector Search' }).nth(1).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('cell', { name: 'Edit Delete' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
});