import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://v2.dev.lilyogis.in/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('rishav.r@rocketlearning.org');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Rishabh1309!@');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://v2.dev.lilyogis.in/');
  await page.getByText('Demographics').click();
  await page.getByText('Countries', { exact: true }).click();
  await page.getByRole('link', { name: 'Browse Countries' }).click();
  await page.getByRole('row', { name: 'PER Peru Aug 6, 2025 Edit' }).getByRole('link').click();
  await page.getByText('Country Details').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('row', { name: 'PER Peru Aug 6, 2025 Edit' }).getByRole('link').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('row', { name: 'PER Peru Aug 6, 2025 Edit' }).getByRole('link').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).fill('');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByText('Country Code * Country Name').click();
  await page.getByText('Country Code * Country Name').click();
  await page.getByRole('textbox', { name: 'Country Name *' }).fill('hgh');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('row', { name: 'PER Hgh Aug 6, 2025 Edit' }).getByRole('link').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).fill('');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByText('Country Code * Country Name').click();
  await page.getByRole('textbox', { name: 'Country Name *' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).fill('india');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByText('The country name has already').click();
  await page.getByRole('textbox', { name: 'Country Name *' }).dblclick();
  await page.getByRole('textbox', { name: 'Country Name *' }).fill('peru');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('row', { name: 'PER Peru Aug 6, 2025 Edit' }).getByRole('link').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.locator('#countries').getByRole('link').click();
  await page.getByRole('textbox', { name: 'Country Code *' }).click();
  await page.getByRole('textbox', { name: 'Country Name *' }).click();
  await page.getByRole('button', { name: 'Reset' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
});